### ISSUE TITLE
GCM notifications fail after Titanium Backup restore

### ISSUE THREAD

**Issue by zzottel** [vector-im/vector-android#725]
If Riot Android is restored on a new ROM/new device using Titanium Backup, the GCM token is also restored, but doesn't work anymore; the notifications don't reach the device.

This seems to be a common problem with apps restored using TB, including WhatsApp, and as far as I could find out, there seems to be nothing the user can do to trigger the app to re-register at GCM except wiping the app data or reinstalling the app.

Here's a thread on xda-developers regarding the problem: http://forum.xda-developers.com/showthread.php?t=2518958

Sending the MY_PACKAGE_REPLACED intent to all apps as proposed in one of the comments didn't help.

It must be possible to work around this problem as the developer of the app, though, as Threema did re-register at GCM after I restored it.

Would be nice if Riot could do that, too.

**Comment by zzottel** [comment]
I read yesterday that at least in develop, hitting "Clear cache" will also renew the GCM token, which should fix this issue. Can't test myself as I'm not on a rooted phone anymore.

**Comment by Matrixcoffee** [comment]
Correct, this was fixed in #936, and should be included in the recently released 0.6.9.

**Comment by zzottel** [comment]
Ok, so how is this handled here? Should I close my tickets myself when I think they are solved or will the team do that?

**Comment by Matrixcoffee** [comment]
Correction, it's not actually fixed fixed, but #936 makes it so that clearing the cache re-registers with GCM.

**Comment by IIIsToRmIII** [comment]
I did a workaround for this: https://www.heiko-frenzel.de/6/5-fix-android-keine-push-benachrichtigungen-bei-apps-nach-titanium-restore.html

English: https://forum.xda-developers.com/showpost.php?p=73323956&postcount=69

Maybe that helps :)
